version: '3.8'

services:
  image-similarity-service:
    build:
      context: ./image-similarity-service
      dockerfile: Dockerfile
    command: uvicorn server:app --host 0.0.0.0 --port 5000
    volumes:
      - ./image-similarity-service:/app
    ports:
      - "5000:5000"
    env_file:
      - ./image-similarity-service/.env
    networks:
      - image-similarity-service-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api-gateway:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env.dev
    networks:
      - image-similarity-service-network
      - ob-similarity-service-network

  ob-similarity-service:
    build:
      context: ./ob-similarity-service
      dockerfile: Dockerfile

    command: uvicorn server:app --host 0.0.0.0 --port 8001
    volumes:
      - ./ob-similarity-service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./ob-similarity-service/.env
    networks:
      - ob-similarity-service-network

networks:
  image-similarity-service-network:
  ob-similarity-service-network:


